# syntax=docker/dockerfile:1.9

ARG BASE_IMAGE=ubuntu:22.04

# ============================================================
# Stage 1: host-tools 构建阶段
# 执行 ./build.sh host-tools，生成通用软件包组
# ============================================================
FROM ${BASE_IMAGE} AS host-tools

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        locales \
        gettext-base \
        autoconf \
        gawk \
        zlib1g-dev \
        libgmp-dev libmpfr-dev libmpc-dev gnat gprbuild \
        libexpat1-dev \
        libssl-dev \
        flex bison \
        libpcre2-dev libffi-dev \
        libxml2-dev \
        cmake \
        libyaml-dev \
        git \
        curl \
        wget \
        python3 \
        pkg-config \
        && locale-gen zh_CN.UTF-8 \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY . .
RUN mkdir -p ./main/downloads ./main/workbase \
    && mv ./download_packages-cache/* ./main/downloads/ \
    && mv ./host-tools-cache/host-tools ./main/workbase/ \
    && mv ./host-tools-cache/status ./main/workbase/

RUN chmod +x ./main/build.sh \
    && cd ./main \
    && ./build.sh -l bootstrap \
    && ./build.sh -l host-tools

# host-tools 产物统一收集到 /output/host-tools
# RUN mkdir -p /output/host-tools /output/status/{host-tools,bootstrap} \
RUN mkdir -p /output/host-tools/status/host-tools /output/host-tools/host-tools \
    && cp -a ./main/workbase/host-tools/. /output/host-tools/host-tools/ \
    && cp -a ./main/workbase/status/host-tools/. /output/host-tools/status/host-tools/

#     && cp -a ./main/workbase/status/bootstrap/. /output/status/bootstrap/


FROM scratch AS host-tools-builder
COPY --from=host-tools /output/host-tools/. /
